name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t web-tier .

      - name: Push Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag web-tier abhimonk1998/web-tier:latest
          docker push abhimonk1998/web-tier:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to EC2
        run: |
          ssh -i "${{ secrets.EC2_PRIVATE_KEY }}" ubuntu@ec2-18-207-11-106.compute-1.amazonaws.com \
          "docker pull abhimonk1998/web-tier:latest && \
          docker stop app || true && \
          docker rm app || true && \
          docker run -d -p 80:3000 --name app abhimonk1998/web-tier:latest"
